/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthAccountRouteImport } from './routes/auth/account'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthLogoutCallbackRouteImport } from './routes/auth/logout/callback'
import { Route as AuthenticatedQuestsNewRouteImport } from './routes/_authenticated/quests/new'
import { Route as AuthenticatedQuestsQuestIdRouteImport } from './routes/_authenticated/quests/$questId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccountRoute = AuthAccountRouteImport.update({
  id: '/auth/account',
  path: '/auth/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthLogoutCallbackRoute = AuthLogoutCallbackRouteImport.update({
  id: '/auth/logout/callback',
  path: '/auth/logout/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuestsNewRoute = AuthenticatedQuestsNewRouteImport.update({
  id: '/quests/new',
  path: '/quests/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestsQuestIdRoute =
  AuthenticatedQuestsQuestIdRouteImport.update({
    id: '/quests/$questId',
    path: '/quests/$questId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/account': typeof AuthAccountRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/quests/$questId': typeof AuthenticatedQuestsQuestIdRoute
  '/quests/new': typeof AuthenticatedQuestsNewRoute
  '/auth/logout/callback': typeof AuthLogoutCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/account': typeof AuthAccountRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/quests/$questId': typeof AuthenticatedQuestsQuestIdRoute
  '/quests/new': typeof AuthenticatedQuestsNewRoute
  '/auth/logout/callback': typeof AuthLogoutCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/account': typeof AuthAccountRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/_authenticated/quests/$questId': typeof AuthenticatedQuestsQuestIdRoute
  '/_authenticated/quests/new': typeof AuthenticatedQuestsNewRoute
  '/auth/logout/callback': typeof AuthLogoutCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/account'
    | '/auth/callback'
    | '/auth/error'
    | '/quests/$questId'
    | '/quests/new'
    | '/auth/logout/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/account'
    | '/auth/callback'
    | '/auth/error'
    | '/quests/$questId'
    | '/quests/new'
    | '/auth/logout/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/auth/account'
    | '/auth/callback'
    | '/auth/error'
    | '/_authenticated/quests/$questId'
    | '/_authenticated/quests/new'
    | '/auth/logout/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthAccountRoute: typeof AuthAccountRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthLogoutCallbackRoute: typeof AuthLogoutCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/account': {
      id: '/auth/account'
      path: '/auth/account'
      fullPath: '/auth/account'
      preLoaderRoute: typeof AuthAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/logout/callback': {
      id: '/auth/logout/callback'
      path: '/auth/logout/callback'
      fullPath: '/auth/logout/callback'
      preLoaderRoute: typeof AuthLogoutCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quests/new': {
      id: '/_authenticated/quests/new'
      path: '/quests/new'
      fullPath: '/quests/new'
      preLoaderRoute: typeof AuthenticatedQuestsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quests/$questId': {
      id: '/_authenticated/quests/$questId'
      path: '/quests/$questId'
      fullPath: '/quests/$questId'
      preLoaderRoute: typeof AuthenticatedQuestsQuestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedQuestsQuestIdRoute: typeof AuthenticatedQuestsQuestIdRoute
  AuthenticatedQuestsNewRoute: typeof AuthenticatedQuestsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedQuestsQuestIdRoute: AuthenticatedQuestsQuestIdRoute,
  AuthenticatedQuestsNewRoute: AuthenticatedQuestsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthAccountRoute: AuthAccountRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthLogoutCallbackRoute: AuthLogoutCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
